uaa_ldap_credentials_password: ((uaa_ldap_password))
pivotal-container-service_pks_tls_certificate: ((pivotal-container-service/pks_tls.certificate))
pivotal-container-service_pks_tls_privatekey: ((pivotal-container-service/pks_tls.private_key))
