pks_api_hostname: api.pks.pcf-aws.jagapps.co
network_name: pks
service_network_name: pks-services
singleton_availability_zone: us-east-1d

cloud_provider_aws_iam_instance_profile_master: pcf-aws_pks-master
cloud_provider_aws_iam_instance_profile_worker: pcf-aws_pks-worker

uaa_ldap_url: ldaps://ldap.jumpcloud.com:636
uaa_ldap_credentials_identity: uid=pksbindjaime,ou=Users,o=5ca651a9852eac5d7270fe5a,dc=jumpcloud,dc=com
uaa_ldap_search_base: ou=Users,o=5ca651a9852eac5d7270fe5a,dc=jumpcloud,dc=com
uaa_ldap_search_filter: uid={0}
uaa_ldap_group_search_base: ou=Users,o=5ca651a9852eac5d7270fe5a,dc=jumpcloud,dc=com
uaa_ldap_group_search_filter: member={0}
uaa_ldap_first_name_attribute: givenName
uaa_ldap_last_name_attribute: sn
uaa_ldap_mail_attribute_name: mail
uaa_ldap_ldap_referrals:
uaa_ldap_external_groups_whitelist: admins,clusteradmins,auditors,developers
oidc_selector_enabled_username_prefix: 'oidc:'
oidc_selector_enabled_username_claim: user_name
oidc_selector_enabled_groups_prefix: 'oidc:'
oidc_selector_enabled_groups_claim: roles

az2_name: us-east-1e
az3_name: us-east-1f

pivotal-container-service_elb_names: [alb:pcf-aws-pks-tg-8443,alb:pcf-aws-pks-tg-9021]
pivotal-container-service_additional_vm_extensions: [pks-api-lb-security-groups]

plan1_selector_active_name: "small"
plan1_selector_active_description: "1 master, 3 workers with privileged containers"
plan1_selector_active_master_az_placement: [us-east-1d]
plan1_selector_active_worker_az_placement: [us-east-1d,us-east-1f]
plan1_selector_active_errand_vm_type: t3.micro
plan1_selector_active_master_persistent_disk_type: "20480"
plan1_selector_active_master_vm_type: m5.large
plan1_selector_active_worker_persistent_disk_type: "102400"
plan1_selector_active_worker_vm_type: m5.large
plan1_selector_active_allow_privileged_containers: true
plan1_selector_active_worker_instances: 3

plan2_selector_active_name: "medium"
plan2_selector_active_description: "3 masters, 3 workers with privileged containers"
plan2_selector_active_master_az_placement: [us-east-1d,us-east-1f]
plan2_selector_active_worker_az_placement: [us-east-1d,us-east-1f]
plan2_selector_active_errand_vm_type: t3.micro
plan2_selector_active_master_persistent_disk_type: "20480"
plan2_selector_active_master_vm_type: m5.large
plan2_selector_active_worker_persistent_disk_type: "102400"
plan2_selector_active_worker_vm_type: m5.large
plan2_selector_active_allow_privileged_containers: true
plan2_selector_active_disable_deny_escalating_exec: true
plan2_selector_active_master_instances: 3
plan2_selector_active_max_worker_instances: 50
plan2_selector_active_worker_instances: 3

upgrade-all-service-instances_post_deploy_state: off
